# Generated by Django 4.0 on 2023-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Pending', 'Pending')], max_length=15),
        ),
    ]
